name: worldedit-selection-viewer
version: '${project.version}'
main: com.funnyboyroks.worldeditselectionviewer.WorldeditSelectionViewer
api-version: 1.19
loadbefore: [ 'WorldEdit' ]
depend: [ 'WorldEdit' ]
author: funnyboy_roks
permissions:
  worldedit-selection-viewer.view:
    description: Ability to view the selection
    default: true
